# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  node: circleci/node@4.2.0
jobs:
  unit-tests:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - run:
        command: npm run unit-tests
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  testing:
    # Run the welcome/run job in its own container
    jobs:
      - unit-tests
